### ISSUE TITLE
Remove requirement for external ssh server

### ISSUE THREAD

**Issue by guanzhangrtk** [wsvn53/scrcpy-ios#1]
First off, this is really cool, I've wanted [this feature](https://github.com/Genymobile/scrcpy/issues/1739) since 2020 :-)

Anyways I have also been looking into this personally, and have been playing around with [iSH](https://github.com/ish-app/ish). Basically it's a x86 emulator that can run a basic Linux shell based on Alpine Linux, and you can setup things like ssh server and other lightweight programs. I have tested and `adb` and `scrcpy` both "function", although for `scrcpy` the issue is X is really slow so it wouldn't really perform very well even if we get it going.

However, with your tools, perhaps we can use iSH to run the ssh-server/adb instead of having a need for an external one. This would only work if your Android device is accessible via the network.

Alternatively, I was wondering if we can build a node app based on https://github.com/yume-chan/ya-webadb to run entirely on iOS.

Something to think about -- I'll try to spend some time to test this out later and see how far I can get, thanks!

**Comment by wsvn53** [comment]
For now, using ssh to connect to adb is the "cheapest" and most stable solution, and maybe I'll investigate using the adb iOS version instead in the future, but there are no plans yet.

**Comment by wsvn53** [comment]
Hi, I think you can also setup a ssh server in your Android device with Termux installed, You won't be required an external ssh server after that. Please check the newest README [https://github.com/wsvn53/scrcpy-ios/#1-setup-a-ssh-server](https://github.com/wsvn53/scrcpy-ios/#1-setup-a-ssh-server)

**Comment by guanzhangrtk** [comment]
Will **all** network traffic from iOS still be sent to the Android device running sshd/Termux? Thanks!

**Comment by wsvn53** [comment]
Yes, all remote control trafic and screen trafic will be sent to ssh port on Android device.

**Comment by guanzhangrtk** [comment]
Oh, so it's only traffic relevant to scrcpy-ios? If so you should probably reflect that in the README. When I first read it I was assuming *all* traffic (including things like web browsing traffic) gets re-directed to the SSH server. I guess that makes sense because each app should be sandboxed and can only access its own traffic and not traffic of other apps running on the device. Thanks!
