### ISSUE TITLE
Add scrcpy screen-off mode

### ISSUE THREAD

**Issue by mutsumi63** [wsvn53/scrcpy-ios#10]

**Comment by wsvn53** [comment]
Pls checkout v2.0 I just released which already supports screen-off option: https://github.com/wsvn53/scrcpy-ios/releases/tag/v2.0

**Comment by mutsumi63** [comment]
> Pls checkout v2.0 I just released which already supports screen-off option: https://github.com/wsvn53/scrcpy-ios/releases/tag/v2.0

Thank you
