### ISSUE TITLE
Add more bitrate option 

### ISSUE THREAD

**Issue by mutsumi63** [wsvn53/scrcpy-ios#11]
pls add more high bitrate option  (for local network)  
like 10m 20m  30m or cutstom bitrate option

**Comment by wsvn53** [comment]
Thanks for your suggestion, please check the latest version of Scrcpy.app https://github.com/wsvn53/scrcpy-ios/releases/tag/v2.3

I have changed bitrate to stepper component, so you can custom with "+" or "-"

**Comment by mutsumi63** [comment]
thank you
