### ISSUE TITLE
Connect problem

### ISSUE THREAD

**Issue by Sun930391** [wsvn53/scrcpy-ios#13]
Hi! Dear author,Ihave try to connect 2 devices as same settings. I only connect one device at a time.One of  them successful. It works very well.But the other one does not.Can you help me to fix it?Thanks a lot. The Android system version is 7.0. Sshd and Android tools are installed and running on this devices.
![EE087437-571E-4B92-AC37-B84A792A5808](https://user-images.githubusercontent.com/97497100/148882882-0c819ff5-f495-458f-a016-6e3925890b2d.png)

**Comment by wsvn53** [comment]
Can you provide me the full logs by click top-right "..." menu item "Show Scrcpy Logs"?

**Comment by Sun930391** [comment]
> Can you provide me the full logs by click top-right "..." menu item "Show Scrcpy Logs"?

Thanks for your help.I try it but there is no Logs button.Only 2 bottoms:Copy URL Scheme and Clear Scrcpy Form.I need install other version?Now is v2.2
![Uploading 2FA90CBF-DC12-46FC-B769-6DA0B8C7FE54.png…]()

**Comment by Sun930391** [comment]
> 

Thanks for your help.I try it but there is no button.I need install other version?Now is v2.2.

> Can you provide me the full logs by click top-right "..." menu item "Show Scrcpy Logs"?

Hello scrcpy v1.21
ACTION> Dismiss
Data: (null)
Error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"
Time Remaining: 1.797693134862316e+308
Time Remaining: 1.797693134862316e+308
Time Remaining: 1.797693134862316e+308
Hello scrcpy v1.21
ACTION> Show Scrcpy Logs
Data: (null)
Error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"
Time Remaining: 1.797693134862316e+308
Hello scrcpy v1.21
Time Remaining: 1.797693134862316e+308
Data: {length = 1, bytes = 0x53}
Error: (null)
CMD> adb get-serialno
DEBUG: Screensaver enabled
RET> [adb get-serialno] (1)
DEBUG: Device serial: emulator-5554
DEBUG: Using server: $TMPDIR/share/scrcpy/scrcpy-server
RET> Upload [/private/var/containers/Bundle/Application/853132A3-1075-42C1-94D0-869B34CC0CCC/App.app/scrcpy-server] => [$TMPDIR/share/scrcpy/scrcpy-server] (YES)
CMD> adb -s emulator-5554 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
RET> [adb -s emulator-5554 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar] (1)
CMD> adb -s emulator-5554 reverse localabstract:scrcpy tcp:27183
RET> [adb -s emulator-5554 reverse localabstract:scrcpy tcp:27183] (0)
CMD> adb -s emulator-5554 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.21 log_level=debug bit_rate=3000000 max_fps=60
RET> [adb -s emulator-5554 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.21 log_level=debug bit_rate=3000000 max_fps=60] (1)
DEBUG: Interrupting socket
DEBUG: Server disconnected
DEBUG: Server terminated
ACTION> Show Scrcpy Logs


Can you give me some help?

**Comment by wsvn53** [comment]
Are you connecting two or more devices at the same time via the same ssh server?

**Comment by Sun930391** [comment]
> Are you connecting two or more devices at the same time via the same ssh server?

No.Just one devices every time.The ssh server run in each Android devices.It work well on a vivo devices without PC.The ssh server and adb server run on the phone.I think the settings are correct.But it doesn’t work on a Samsung devices with same steps and settings.

**Comment by Sun930391** [comment]
Samsung devices work well on windows.

**Comment by wsvn53** [comment]
> > Are you connecting two or more devices at the same time via the same ssh server?
> 
> No.Just one devices every time.The ssh server run in each Android devices.It work well on a vivo devices without PC.The ssh server and adb server run on the phone.I think the settings are correct.But it doesn’t work on a Samsung devices with same steps and settings.

Can you execute `adb devices` on your Termux which installed on your Samsung phone?

**Comment by wsvn53** [comment]
> > > Are you connecting two or more devices at the same time via the same ssh server?
> > 
> > 
> > No.Just one devices every time.The ssh server run in each Android devices.It work well on a vivo devices without PC.The ssh server and adb server run on the phone.I think the settings are correct.But it doesn’t work on a Samsung devices with same steps and settings.
> 
> Can you execute `adb devices` on your Termux which installed on your Samsung phone?

Then, try to execute `adb -s emulator-5554 reverse localabstract:scrcpy tcp:27183` to see what happens.

**Comment by Sun930391** [comment]
> adb -s emulator-5554 reverse localabstract:scrcpy tcp:27183

~ $ adb devices
List of devices attached
emulator-5554   device

~ $ adb -s emulator-5554 reverse localabstract:scrcpy tcp:27183
adb: error: more than one device/emulator
~ $

I think it’s Samsung device’s problem.It display more than one device.Actually it just one device.Your app work well.

**Comment by wsvn53** [comment]
It seems there are some known issues on adb reverse over tcpip. scrcpy's workaround is try to switch to `adb forward` https://github.com/Genymobile/scrcpy/issues/5

But, scrcpy iOS app have not adaptived with adb forward now. I'm planning to adaptive this.

As you said befor `Samsung devices work well on windows`, have you tried to connect your Samsung via tcpip but not usb and use scrcpy on windows?

**Comment by Sun930391** [comment]
> It seems there are some known issues on adb reverse over tcpip. scrcpy's workaround is try to switch to `adb forward` [Genymobile/scrcpy#5](https://github.com/Genymobile/scrcpy/issues/5)
> 
> But, scrcpy iOS app have not adaptived with adb forward now. I'm planning to adaptive this.
> 
> As you said befor `Samsung devices work well on windows`, have you tried to connect your Samsung via tcpip but not usb and use scrcpy on windows?

Yes,it work well on windows via tcpip not usb.Here are some logs.

scrcpy 1.21 <https://github.com/Genymobile/scrcpy>
D:\scrcpy-win64-v1.21\scrcpy-server: 1 file pushed, 0 skipped. 9.3 MB/s (40067 bytes in 0.004s)
adb.exe: error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
[server] INFO: Device: samsung SM-N935F (Android 8.0.0)
INFO: Renderer: direct3d
INFO: Initial texture: 1440x2560

**Comment by wsvn53** [comment]
> > It seems there are some known issues on adb reverse over tcpip. scrcpy's workaround is try to switch to `adb forward` [Genymobile/scrcpy#5](https://github.com/Genymobile/scrcpy/issues/5)
> > But, scrcpy iOS app have not adaptived with adb forward now. I'm planning to adaptive this.
> > As you said befor `Samsung devices work well on windows`, have you tried to connect your Samsung via tcpip but not usb and use scrcpy on windows?
> 
> Yes,it work well on windows via tcpip not usb.Here are some logs.
> 
> scrcpy 1.21 https://github.com/Genymobile/scrcpy D:\scrcpy-win64-v1.21\scrcpy-server: 1 file pushed, 0 skipped. 9.3 MB/s (40067 bytes in 0.004s) adb.exe: error: more than one device/emulator ERROR: "adb reverse" returned with value 1 WARN: 'adb reverse' failed, fallback to 'adb forward' [server] INFO: Device: samsung SM-N935F (Android 8.0.0) INFO: Renderer: direct3d INFO: Initial texture: 1440x2560

Got it, it looks like it can be fixed by `adb forward`, I will try.

**Comment by Sun930391** [comment]
> > > It seems there are some known issues on adb reverse over tcpip. scrcpy's workaround is try to switch to `adb forward` [Genymobile/scrcpy#5](https://github.com/Genymobile/scrcpy/issues/5)
> > > But, scrcpy iOS app have not adaptived with adb forward now. I'm planning to adaptive this.
> > > As you said befor `Samsung devices work well on windows`, have you tried to connect your Samsung via tcpip but not usb and use scrcpy on windows?
> > 
> > 
> > Yes,it work well on windows via tcpip not usb.Here are some logs.
> > scrcpy 1.21 https://github.com/Genymobile/scrcpy D:\scrcpy-win64-v1.21\scrcpy-server: 1 file pushed, 0 skipped. 9.3 MB/s (40067 bytes in 0.004s) adb.exe: error: more than one device/emulator ERROR: "adb reverse" returned with value 1 WARN: 'adb reverse' failed, fallback to 'adb forward' [server] INFO: Device: samsung SM-N935F (Android 8.0.0) INFO: Renderer: direct3d INFO: Initial texture: 1440x2560
> 
> Got it, it looks like it can be fixed by `adb forward`, I will try.

Thanks for you help. Looking forward to good news.

**Comment by wsvn53** [comment]
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7862353/Scrcpy.ipa.zip)

Hi, can you try to use this version to connect your Samsung Android? And give me a feedback, thanks.

**Comment by mutsumi63** [comment]
Probably Termux's ADB or System problem , I have same problem.
I connect phone by wifiadb ip and specify device serial  wifiadb ip.
It  work fine.

**Comment by mutsumi63** [comment]
You can try open wifiadb and specify device serial option emulator-5554 or wifiadb’s ip

**Comment by Sun930391** [comment]
> [Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7862353/Scrcpy.ipa.zip)
> 
> Hi, can you try to use this version to connect your Samsung Android? And give me a feedback, thanks.

It work well with Force Adb Forward.It’s perfect!Thank you for your help.

**Comment by Sun930391** [comment]
> You can try open wifiadb and specify device serial option emulator-5554 or wifiadb’s ip

I have try this ,it doesn’t work.Now the author fix it,it work well now.

**Comment by wsvn53** [comment]
> > [Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7862353/Scrcpy.ipa.zip)
> > Hi, can you try to use this version to connect your Samsung Android? And give me a feedback, thanks.
> 
> It work well with Force Adb Forward.It’s perfect!Thank you for your help.

Can you try to disable `Force ADB Forward` and connect again? I would like to know if the automatic fallback to `adb forward` is working.

**Comment by Sun930391** [comment]
> > > [Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7862353/Scrcpy.ipa.zip)
> > > Hi, can you try to use this version to connect your Samsung Android? And give me a feedback, thanks.
> > 
> > 
> > It work well with Force Adb Forward.It’s perfect!Thank you for your help.
> 
> Can you try to disable `Force ADB Forward` and connect again? I would like to know if the automatic fallback to `adb forward` is working.

It doesn’t work.I remember the tips as same as before version 2.3.Just like the pic on the top.I will try again next week.

**Comment by Sun930391** [comment]
![D7E6A71E-7C62-4565-AED3-C99735D8194E](https://user-images.githubusercontent.com/97497100/149669319-3ebd6ec4-626c-4f23-967d-ed046a924058.png)
Here is a screenshot,just like before.

**Comment by wsvn53** [comment]
Hi, @Sun930391 can you try this version with "Force ADB Forward" disabled? I want to check if I've fixed the issue that fallback to `adb forward` when `adb reverse` failed.
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7882935/Scrcpy.ipa.zip)

**Comment by Sun930391** [comment]
> Hi, @Sun930391 can you try this version with "Force ADB Forward" disabled? I want to check if I've fixed the issue that fallback to `adb forward` when `adb reverse` failed.
> [Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7882935/Scrcpy.ipa.zip)

It work well with "Force ADB Forward" disabled.I think you fixed it.Good job!👍

**Comment by wsvn53** [comment]
That's good, thanks for your feedback.

**Comment by Sun930391** [comment]
> That's good, thanks for your feedback.

You’re welcome. Thank you for your hard work .I’m happy to do something for you.I have a new idea.The server option maybe pull down button.The history servers maybe saved.I can connect multiple devices faster.Now I need type the server address every time.

**Comment by Sun930391** [comment]
Add a button just like “Add Server” for multiple address .And I can choose a saved server address faster.This is my suggestion,maybe you have a better idea.

**Comment by wsvn53** [comment]
> > That's good, thanks for your feedback.
> 
> You’re welcome. Thank you for your hard work .I’m happy to do something for you.I have a new idea.The server option maybe pull down button.The history servers maybe saved.I can connect multiple devices faster.Now I need type the server address every time.
> 

According to your requirement, I strongly recommend that you copy the connect information into a URL scheme and add it to the home screen, so that you can switch between different mobile phone connections very quickly. You just need to fill in the information and click on the top-right menu ... then click `Copy URL Scheme`, and use the system app `Shortcuts` to add to home screen.

**Comment by Sun930391** [comment]
> > > That's good, thanks for your feedback.
> > 
> > 
> > You’re welcome. Thank you for your hard work .I’m happy to do something for you.I have a new idea.The server option maybe pull down button.The history servers maybe saved.I can connect multiple devices faster.Now I need type the server address every time.
> 
> According to your requirement, I strongly recommend that you copy the connect information into a URL scheme and add it to the home screen, so that you can switch between different mobile phone connections very quickly. You just need to fill in the information and click on the top-right menu ... then click `Copy URL Scheme`, and use the system app `Shortcuts` to add to home screen.

I have try it.It’s really cool.I didn’t notice before.Thanks again.
