### ISSUE TITLE
Cannot use together with gost

### ISSUE THREAD

**Issue by forrestsocool** [wsvn53/scrcpy-ios#14]
gost is a network proxy tool written by go，
when I use scrcpy-ios client with a server running gost,
the app log shows error "main.go:88 listen tcp: xxx:bind:address alredy in use ...", the xxx is the port used by gost.

**Comment by wsvn53** [comment]
So, are your using gost as a proxy tunnel for your ssh server in your local network?

**Comment by wsvn53** [comment]
Can you provide more informations, inlcude the Scrcpy logs that you can copy from top-right "..." menu action.

**Comment by forrestsocool** [comment]
> So, are your using gost as a proxy tunnel for your ssh server in your local network?

No，actually,  I used gost to redirect a mining pool, like:  gost -L=tcp://:12345/pool.minexmr.com:4444 -F=relay+tls://138.3.XXX.XXX:8443
138.3.XXX.XXX is another oversea vps's IP.  and 12345 or 8443 is the port conflict with scrcpy-ios

here is the log:


Hello scrcpy v1.21
Data: {length = 1, bytes = 0x53}
Error: (null)
CMD> adb get-serialno
DEBUG: Screensaver enabled
ERROR: Could not get device serial
ERROR: Server connection failed
Scrcpy STOPPED.
DEBUG: Screensaver enabled
CMD> adb get-serialno
RET> [adb get-serialno] (1)
DEBUG: Device serial: localhost:5411
2022/01/14 07:16:32 main.go:88: listen tcp :8443: bind: address already in use
DEBUG: Using server: $TMPDIR/share/scrcpy/scrcpy-server
RET> Upload [/private/var/containers/Bundle/Application/5E308FA6-9E86-4391-AC8F-D65C84819977/App.app/scrcpy-server] => [$TMPDIR/share/scrcpy/scrcpy-server] (YES)
CMD> adb -s localhost:5411
2022/01/14 07:16:32 main.go:88: listen tcp :8443: bind: address already in use push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
RET> [adb -s localhost:5411
2022/01/14 07:16:32 main.go:88: listen tcp :8443: bind: address already in use push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar] (0)
ERROR: Server connection failed
Scrcpy STOPPED.
ACTION> Show Scrcpy Logs
ACTION> Show Scrcpy Logs

**Comment by wsvn53** [comment]
> adb -s localhost:5411
2022/01/14 07:16:32 main.go:88: listen tcp :8443: bind: address already in use push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar

The log you provided is very strange, it looks like a piece of your gost error message was inserted when executing the command on the ssh server. Can you confirm your configuration? Are the gost commands running repeatedly on the server?

**Comment by wsvn53** [comment]
Or can you check your /etc/profile or ~/.profile and ~/.bash_profile, is there any auto start commands defined in these files? That may caused the gost executed when scrcpy executing some adb commands.

**Comment by forrestsocool** [comment]
yes，I added some start command in /etc/profile ，after remove these it works, thank you!
