### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chc880** [wsvn53/scrcpy-ios#15]
Hello scrcpy v1.21
Data: {length = 1, bytes = 0x53}
Error: (null)
CMD> adb get-serialno
DEBUG: Screensaver enabled
RET> [adb get-serialno] (YES)
DEBUG: Device serial: [0;1;34;94m┌────────────[0;34m────────────[0;37m─────────────[0;1;30;90m────────┐[0m
[0;1;34;94m│[0m                                             [0;1;30;90m│[0m
[0;1;34;94m│[0m [0;1;34;94mmmmmm[0m                         [0;37mm[0m       [0;1;30;90m""#[0m   [0;34m│[0m
[0;1;34;94m│[0m   [0;34m#[0m   [0;34mmmmmm[0m [0;34mm[0;37mmmmm[0m  [0;37mmmm[0m  [0;37mm[0m[0;1;30;90mmm[0m [0;1;30;90mmm#mm[0m  [0;1;30;90mmmm[0m  [0;1;34;94m#[0m   [0;34m│[0m
[0;37m│[0m   [0;34m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#"[0m [0;1;30;90m"#[0m [0;1;30;90m#"[0m [0;1;30;90m"[0m  [0;1;30;90m#[0m   [0;1;34;94m"[0m   [0;1;34;94m#[0m [0;1;34;94m#[0m   [0;34m│[0m
[0;37m│[0m   [0;37m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m   [0;1;30;90m#[0m [0;1;30;90m#[0m     [0;1;34;94m#[0m   [0;1;34;94mm"""#[0m [0;34m#[0m   [0;1;34;94m│[0m
[0;37m│[0m [0;37mmm#mm[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m"#[0;1;34;94mm#"[0m [0;1;34;94m#[0m     [0;1;34;94m"m[0;34mm[0m [0;34m"mm"#[0m [0;34m"mm[0m [0;1;34;94m│[0m
[0;1;30;90m│[0m                                             [0;37m│[0m
[0;1;30;90m│[0;34m───────────────────[0;1;34;94m────────────[0;37m──────────────│[0m
[0;1;30;90m│[0m            [0;1;35;92mImmortalWrt[0m [0;1;35;92mSNAPSHOT[0m             [0;37m│[0m
[0;1;34;94m└[0;1;34;94m─────────────[0;34m──────────────[0;1;30;90m───────────[0;37m───────┘[0m
10.0.10.101:5555
DEBUG: Using server: $TMPDIR/share/scrcpy/scrcpy-server
RET> Upload [/private/var/containers/Bundle/Application/A43D1E3D-D304-42B3-B097-6704F146C686/App.app/scrcpy-server] => [$TMPDIR/share/scrcpy/scrcpy-server] (YES)
CMD> adb -s [0;1;34;94m‚îå‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îê[0m
[0;1;34;94m‚îÇ[0m                                             [0;1;30;90m‚îÇ[0m
[0;1;34;94m‚îÇ[0m [0;1;34;94mmmmmm[0m                         [0;37mm[0m       [0;1;30;90m""#[0m   [0;34m‚îÇ[0m
[0;1;34;94m‚îÇ[0m   [0;34m#[0m   [0;34mmmmmm[0m [0;34mm[0;37mmmmm[0m  [0;37mmmm[0m  [0;37mm[0m[0;1;30;90mmm[0m [0;1;30;90mmm#mm[0m  [0;1;30;90mmmm[0m  [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;34m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#"[0m [0;1;30;90m"#[0m [0;1;30;90m#"[0m [0;1;30;90m"[0m  [0;1;30;90m#[0m   [0;1;34;94m"[0m   [0;1;34;94m#[0m [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;37m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m   [0;1;30;90m#[0m [0;1;30;90m#[0m     [0;1;34;94m#[0m   [0;1;34;94mm"""#[0m [0;34m#[0m   [0;1;34;94m‚îÇ[0m
[0;37m‚îÇ[0m [0;37mmm#mm[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m"#[0;1;34;94mm#"[0m [0;1;34;94m#[0m     [0;1;34;94m"m[0;34mm[0m [0;34m"mm"#[0m [0;34m"mm[0m [0;1;34;94m‚îÇ[0m
[0;1;30;90m‚îÇ[0m                                             [0;37m‚îÇ[0m
[0;1;30;90m‚îÇ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÇ[0m
[0;1;30;90m‚îÇ[0m            [0;1;35;92mImmortalWrt[0m [0;1;35;92mSNAPSHOT[0m             [0;37m‚îÇ[0m
[0;1;34;94m‚îî[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îò[0m
10.0.10.101:5555 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
RET> [adb -s [0;1;34;94m‚îå‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îê[0m
[0;1;34;94m‚îÇ[0m                                             [0;1;30;90m‚îÇ[0m
[0;1;34;94m‚îÇ[0m [0;1;34;94mmmmmm[0m                         [0;37mm[0m       [0;1;30;90m""#[0m   [0;34m‚îÇ[0m
[0;1;34;94m‚îÇ[0m   [0;34m#[0m   [0;34mmmmmm[0m [0;34mm[0;37mmmmm[0m  [0;37mmmm[0m  [0;37mm[0m[0;1;30;90mmm[0m [0;1;30;90mmm#mm[0m  [0;1;30;90mmmm[0m  [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;34m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#"[0m [0;1;30;90m"#[0m [0;1;30;90m#"[0m [0;1;30;90m"[0m  [0;1;30;90m#[0m   [0;1;34;94m"[0m   [0;1;34;94m#[0m [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;37m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m   [0;1;30;90m#[0m [0;1;30;90m#[0m     [0;1;34;94m#[0m   [0;1;34;94mm"""#[0m [0;34m#[0m   [0;1;34;94m‚îÇ[0m
[0;37m‚îÇ[0m [0;37mmm#mm[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m"#[0;1;34;94mm#"[0m [0;1;34;94m#[0m     [0;1;34;94m"m[0;34mm[0m [0;34m"mm"#[0m [0;34m"mm[0m [0;1;34;94m‚îÇ[0m
[0;1;30;90m‚îÇ[0m                                             [0;37m‚îÇ[0m
[0;1;30;90m‚îÇ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÇ[0m
[0;1;30;90m‚îÇ[0m            [0;1;35;92mImmortalWrt[0m [0;1;35;92mSNAPSHOT[0m             [0;37m‚îÇ[0m
[0;1;34;94m‚îî[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îò[0m
10.0.10.101:5555 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar] (NO)
> Pending Error: Error Domain=go Code=1 "CMD> adb -s [0;1;34;94m‚îå‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îê[0m
[0;1;34;94m‚îÇ[0m                                             [0;1;30;90m‚îÇ[0m
[0;1;34;94m‚îÇ[0m [0;1;34;94mmmmmm[0m                         [0;37mm[0m       [0;1;30;90m""#[0m   [0;34m‚îÇ[0m
[0;1;34;94m‚îÇ[0m   [0;34m#[0m   [0;34mmmmmm[0m [0;34mm[0;37mmmmm[0m  [0;37mmmm[0m  [0;37mm[0m[0;1;30;90mmm[0m [0;1;30;90mmm#mm[0m  [0;1;30;90mmmm[0m  [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;34m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#"[0m [0;1;30;90m"#[0m [0;1;30;90m#"[0m [0;1;30;90m"[0m  [0;1;30;90m#[0m   [0;1;34;94m"[0m   [0;1;34;94m#[0m [0;1;34;94m#[0m   [0;34m‚îÇ[0m
[0;37m‚îÇ[0m   [0;37m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m   [0;1;30;90m#[0m [0;1;30;90m#[0m     [0;1;34;94m#[0m   [0;1;34;94mm"""#[0m [0;34m#[0m   [0;1;34;94m‚îÇ[0m
[0;37m‚îÇ[0m [0;37mmm#mm[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m"#[0;1;34;94mm#"[0m [0;1;34;94m#[0m     [0;1;34;94m"m[0;34mm[0m [0;34m"mm"#[0m [0;34m"mm[0m [0;1;34;94m‚îÇ[0m
[0;1;30;90m‚îÇ[0m                                             [0;37m‚îÇ[0m
[0;1;30;90m‚îÇ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÇ[0m
[0;1;30;90m‚îÇ[0m            [0;1;35;92mImmortalWrt[0m [0;1;35;92mSNAPSHOT[0m             [0;37m‚îÇ[0m
[0;1;34;94m‚îî[0;1;34;94m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;34m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;1;30;90m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0;37m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îò[0m
10.0.10.101:5555 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
OUTPUT> [0;1;34;94m┌────────────[0;34m────────────[0;37m─────────────[0;1;30;90m────────┐[0m
[0;1;34;94m│[0m                                             [0;1;30;90m│[0m
[0;1;34;94m│[0m [0;1;34;94mmmmmm[0m                         [0;37mm[0m       [0;1;30;90m""#[0m   [0;34m│[0m
[0;1;34;94m│[0m   [0;34m#[0m   [0;34mmmmmm[0m [0;34mm[0;37mmmmm[0m  [0;37mmmm[0m  [0;37mm[0m[0;1;30;90mmm[0m [0;1;30;90mmm#mm[0m  [0;1;30;90mmmm[0m  [0;1;34;94m#[0m   [0;34m│[0m
[0;37m│[0m   [0;34m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#"[0m [0;1;30;90m"#[0m [0;1;30;90m#"[0m [0;1;30;90m"[0m  [0;1;30;90m#[0m   [0;1;34;94m"[0m   [0;1;34;94m#[0m [0;1;34;94m#[0m   [0;34m│[0m
[0;37m│[0m   [0;37m#[0m   [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;37m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m   [0;1;30;90m#[0m [0;1;30;90m#[0m     [0;1;34;94m#[0m   [0;1;34;94mm"""#[0m [0;34m#[0m   [0;1;34;94m│[0m
[0;37m│[0m [0;37mmm#mm[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m#[0m [0;1;30;90m"#[0;1;34;94mm#"[0m [0;1;34;94m#[0m     [0;1;34;94m"m[0;34mm[0m [0;34m"mm"#[0m [0;34m"mm[0m [0;1;34;94m│[0m
[0;1;30;90m│[0m                                             [0;37m│[0m
[0;1;30;90m│[0;34m───────────────────[0;1;34;94m────────────[0;37m──────────────│[0m
[0;1;30;90m│[0m            [0;1;35;92mImmortalWrt[0m [0;1;35;92mSNAPSHOT[0m             [0;37m│[0m
[0;1;34;94m└[0;1;34;94m─────────────[0;34m──────────────[0;1;30;90m───────────[0;37m───────┘[0m

**Comment by chc880** [comment]
Solved  by set $TEMDIR

**Comment by chc880** [comment]
你好，大佬
由于这个项目需要构建一个ssh server作为跳板，所以我正在尝试构建一个比较稳定的环境去作为跳板，以此保证连接的稳定。
我测试了虚拟机构建一个Ubuntu，手机上Termux，都能成功连接到手机。但是在使用macOS(intel)和openwrt(R4S)作为ssh server时，就会报以上错误。我确认adb都正确安装，并成功连接。
感谢！

错误开头报：Error Domain=go Code=1 "CMD> adb -s ......
错误信息截图如下：
https://vip2.loli.io/2022/03/23/7PbCstG4jmDzQr1.png

**Comment by chc880** [comment]
好像找到原因了，登录ssh时的欢迎信息似乎穿插到了命令行中，导致运行错误😂，已经解决

**Comment by wsvn53** [comment]
赞，幸好你自己查出来了，否则这种问题我都不知道怎么入手

**Comment by chc880** [comment]
> 赞，幸好你自己查出来了，否则这种问题我都不知道怎么入手

或许可以稍微优化一下，等待欢迎信息载入完成后再进行命令执行。另外，如果需要远程控制，通过内网穿透将ssh映射出去，可能会涉及一些安全性的问题，是否会考虑增加通过证书登录的功能。

**Comment by wsvn53** [comment]
> > 赞，幸好你自己查出来了，否则这种问题我都不知道怎么入手
> 
> 或许可以稍微优化一下，等待欢迎信息载入完成后再进行命令执行。另外，如果需要远程控制，通过内网穿透将ssh映射出去，可能会涉及一些安全性的问题，是否会考虑增加通过证书登录的功能。

已经实现了 adb 移植到 iOS 上，以后就可以直连 adb 端口了，等下一个版本就直接把 ssh 依赖去掉了，用 adb 自身的授权应该安全些。ssh 只是过渡阶段。
