### ISSUE TITLE
How to re-sign the scrcpy.ipa?

### ISSUE THREAD

**Issue by krishtoautomate** [wsvn53/scrcpy-ios#2]
How to re-sign the scrcpy.ipa?

after scrcpy.ipa is re-code signed, how to run with scrcpy?

**Comment by wsvn53** [comment]
You need register as an Apple Developer account $99, then sign in to Xcode, downloads Certificates and ProvisionFiles. You can use a mac app named "iOS App Signer" to re-codesign Scrcpy.ipa.

After re-codesigned, you can use Xcode -> Windows -> Devices & Simulators, plugin your iPhone with Xcode, click "+" in the "INSTALLED APPS" section to install the ipa, or use other tools like iMazing to install it.

If you have not an Apple Developer account, you can send me your email or device UDID (https://get.udid.io) to me, I can codesign to you this time.

**Comment by krishtoautomate** [comment]
Hi Here is my udid
00008101-001C15A20AD2001E
email: tulasikrishna89@gmail.com
I would like to try its working

**Comment by wsvn53** [comment]
Done, you can try this ipa:
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/6873462/Scrcpy.ipa.zip)

**Comment by krishtoautomate** [comment]
working. im able to see my android device screen on my ios device
