### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by Youngv** [wsvn53/scrcpy-ios#3]
## ios ssh to mac: test with Termius work fine
![03B1A600-B4A6-4942-BF17-4BCBB2E732F4](https://user-images.githubusercontent.com/1787625/126891319-6bb05bc1-c6c7-4334-87a8-a087ce4f5907.png)
## adb: test on mac work fine
![image](https://user-images.githubusercontent.com/1787625/126891286-2a09afbb-1626-4d17-affb-6dd15e7887ac.png)
## ios: connect error
![2D018A5B-8441-4859-B2A3-F4AE13D3D15F](https://user-images.githubusercontent.com/1787625/126891304-84dc57b1-ed58-4030-9326-245e8b65a674.png)

**Comment by Youngv** [comment]
Maybe something wrong with the way I sign the app, can you add me to the test group, 
UDID: 00008101-0013295921A0001E

**Comment by wsvn53** [comment]
Sorry, the first time connect to local network after newly installed requires user to allow Local Network Permission, I havn't deal with this case now, you can try to connect again after allow Local Network Permission.

**Comment by Youngv** [comment]
> Sorry, the first time connect to local network after newly installed requires user to allow Local Network Permission, I havn't deal with this case now, you can try to connect again after allow Local Network Permission.

I have already enable the allow Local Network Permission and restart the app several times, but still with the error.

**Comment by wsvn53** [comment]
> > Sorry, the first time connect to local network after newly installed requires user to allow Local Network Permission, I havn't deal with this case now, you can try to connect again after allow Local Network Permission.
> 
> I have already enable the allow Local Network Permission and restart the app several times, but still with the error.

Can you join my telegram group, send me the detail infomatin. https://t.me/joinchat/I_HBlFpB27RkZTRl

**Comment by wsvn53** [comment]
Local Network Permission issue now adapted, please check the newest release.
