### ISSUE TITLE
cannot edit Scrcpy path 

### ISSUE THREAD

**Issue by DriverLin** [wsvn53/scrcpy-ios#4]
I'm trying to use termux as the ssh server to run this , but the Scrcpy path "/tmp/share/scrcpy/scrcpy-server" is permission denied on android . if this path could be specified manually , two devices can be connected without an external device.

**Comment by wsvn53** [comment]
Yes, I'll change <scrcpy-server> to customizable path in a later version.

BTW, have you also installed adb in termux? Scrcpy also requires adb and ssh both.

**Comment by DriverLin** [comment]
![Screenshot_20210802-185537](https://user-images.githubusercontent.com/40745915/127851140-5940522d-f7e0-48ea-991e-8643414cf8d3.jpg)
Sometimes adb can directly connect to itself, the display name is emulator, and more often a wireless connection is needed.

**Comment by wsvn53** [comment]
Can you try to install this ipa, I just changed /tmp directory to env $TMPDIR variable. I have tested on my Android termux and it works without external ssh computer.

[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/6946946/Scrcpy.ipa.zip)

**Comment by DriverLin** [comment]
It also works fine on my device , thanks !
