### ISSUE TITLE
(request) lower the minimum iOS version on releases

### ISSUE THREAD

**Issue by shiypc** [wsvn53/scrcpy-ios#6]
right now, i don't have a computer to compile this, so i would very much appreciate the releases having lower minimum versions, particularly to allow support on my iPhone 11 with 13.5.1, since i have no devices with a newer iOS version

**Comment by wsvn53** [comment]
I just simply changed the deploy version to iOS 13.0, and exported an ipa for you, but I have no iOS 13 device to test. You can try to install this ipa (required re-codesign):

[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7422552/Scrcpy.ipa.zip)
